Repository LuckyVicky-2team/frontend, pull requests merged in 2024-11, with the labels that each got.

#159 Refactor: 리프레시 토큰 로직 수정
  src/actions/AuthActions.ts
  src/api/apis/authApis.ts
  src/api/instance.ts
  src/app/(authentication)/_components/SignupForm/SocialSignupForm/index.tsx
  src/app/main/_components/Footer/Footer.tsx
  src/app/main/page.tsx
  src/app/threads/_components/ChattingRoom/index.tsx
  src/utils/getNewAccessToken.ts
Labels: enhancement

#160 Hotfix: 리프레시 토큰 오류 수정
  src/actions/AuthActions.ts
  src/api/instance.ts
  src/utils/getNewAccessToken.ts
Labels: bug

#162 Fix: songeun-7
  next.config.mjs
  package-lock.json
  package.json
  public/assets/images/spinner.gif
  public/assets/images/spinner2.gif
  src/api/apis/logOutApis.ts
  src/api/queryHooks/gathering.ts
  src/app/api/convert-gif-to-mp4/route.ts
  src/app/gatherings/[id]/_components/GatheringDetails.tsx/index.tsx
  src/app/layout.tsx
  src/app/mypage/_components/Info/Info.tsx
  src/app/test/song/page.tsx
  src/service/initFirebase.ts
  src/service/notificationPermission.ts
  src/utils/detectInAppBrowser.ts
  src/utils/gifToMp4.module.scss
  src/utils/gifToMp4.tsx
Labels: bug

#163 Feat: 쓰레드 컴포넌트 UI 및 기능 구현 & 로그아웃 및 로그인 오류 수정
  src/actions/AuthActions.ts
  src/api/apis/logOutApis.ts
  src/api/instance.ts
  src/app/gatherings/[id]/_components/Members/index.tsx
  src/app/threads/ThreadsPage.module.scss
  src/app/threads/[chatRoomId]/ThreadDetailPage.module.scss
  src/app/threads/_components/ChattingRoom/ChattingRoom.module.scss
  src/app/threads/_components/ChattingRoom/index.tsx
  src/app/threads/_components/GatheringInfoOfThread/index.tsx
  src/app/threads/_components/TalkListItem/TalkListItem.module.scss
  src/app/threads/_components/TalkListItem/index.tsx
  src/app/threads/_components/ThreadList/index.tsx
Labels: bug, enhancement

#165 Fix: songeun 8
  src/api/queryHooks/me.ts
  src/app/gatherings/[id]/_components/KakaoShare/KakaoShare.module.scss
  src/app/gatherings/[id]/_components/KakaoShare/index.tsx
  src/app/gatherings/[id]/_components/ShareModal/ShareModal.module.scss
  src/app/gatherings/[id]/page.tsx
  src/app/layout.tsx
  src/app/main/page.tsx
  src/app/mypage/_components/Info/Info.tsx
  src/components/common/AppInstallPrompt/index.tsx
  src/components/common/ProfileImage/ProfileImage.module.scss
  tmp/input.gif
Labels: bug

#166 Fix: songeun-9
  src/components/common/AppInstallPrompt/index.tsx
Labels: bug

#172 Fix: songeun-10
  global.d.ts
  public/assets/icons/app/android-icon-144x144.png
  public/assets/icons/app/android-icon-192x192.png
  public/assets/icons/app/android-icon-36x36.png
  public/assets/icons/app/android-icon-48x48.png
  public/assets/icons/app/android-icon-72x72.png
  public/assets/icons/app/android-icon-96x96.png
  public/assets/icons/app/apple-icon-114x114.png
  public/assets/icons/app/apple-icon-120x120.png
  public/assets/icons/app/apple-icon-144x144.png
  public/assets/icons/app/apple-icon-152x152.png
  public/assets/icons/app/apple-icon-180x180.png
  public/assets/icons/app/apple-icon-57x57.png
  public/assets/icons/app/apple-icon-60x60.png
  public/assets/icons/app/apple-icon-72x72.png
  public/assets/icons/app/apple-icon-76x76.png
  public/assets/icons/app/apple-icon-precomposed.png
  public/assets/icons/app/apple-icon.png
  public/assets/icons/app/browserconfig.xml
  public/assets/icons/app/favicon-16x16.png
  public/assets/icons/app/favicon-32x32.png
  public/assets/icons/app/favicon-96x96.png
  public/assets/icons/app/favicon.ico
  public/assets/icons/app/manifest.json
  public/assets/icons/app/ms-icon-144x144.png
  public/assets/icons/app/ms-icon-150x150.png
  public/assets/icons/app/ms-icon-310x310.png
  public/assets/icons/app/ms-icon-70x70.png
  src/app/api/convert-gif-to-mp4/route.ts
  src/app/gatherings/[id]/_components/Footer/Footer.module.scss
  src/app/gatherings/[id]/_components/Footer/index.tsx
  src/app/gatherings/[id]/_components/GatheringDetails.tsx/GatheringDetails.module.scss
  src/app/gatherings/[id]/_components/GatheringDetails.tsx/index.tsx
  src/app/gatherings/[id]/_components/Members/index.tsx
  src/app/gatherings/[id]/page.tsx
  src/app/layout.tsx
  src/app/main/page.tsx
  src/app/mypage/settingAlarm/page.tsx
  src/components/common/AppInstallPrompt/MobileInstallPrompt/index.tsx
  src/components/common/AppInstallPrompt/index.tsx
  src/components/common/BottomSheet/BottomSheetFull/BottomSheetFull.module.scss
  src/components/common/BottomSheet/BottomSheetFull/index.tsx
  src/components/common/BottomSheet/index.tsx
  src/components/common/FCMDisabledPrompt/FCMDisabledPrompt.module.scss
  src/components/common/FCMDisabledPrompt/index.tsx
  src/components/common/FindPlaceModal/KakaoList/PlaceListItem/PlaceListItem.module.scss
  src/components/common/FindPlaceModal/KakaoList/PlaceListItem/index.tsx
  src/components/common/Modal/LoginModal/index.tsx
  src/components/common/ProfileImage/ProfileImage.module.scss
  src/components/common/Tag/Tag.module.scss
  src/contexts/pwaContext.tsx
  src/hooks/useInApp.ts
  src/hooks/useScreenWidth.ts
  src/utils/detectInAppBrowser.ts
  src/utils/gifToMp4.tsx
  tmp/input.gif
  tsconfig.json
Labels: bug
