Repository LuckyVicky-2team/frontend, pull requests merged in 2024-08, with the labels that each got.

#40 Feat: 로그인 회원가입 페이지 UI 구현
  package-lock.json
  package.json
  public/assets/fonts/런드리고딕OTF Bold.otf
  public/assets/fonts/런드리고딕OTF Regular.otf
  public/assets/icons/closedEye.svg
  public/assets/icons/google_logo.svg
  public/assets/icons/kakao_logo.svg
  public/assets/icons/logo.svg
  public/assets/icons/openEye.svg
  src/app/(authentication)/AuthLayout.module.scss
  src/app/(authentication)/_components/AuthHeader/AuthHeader.module.scss
  src/app/(authentication)/_components/AuthHeader/index.tsx
  src/app/(authentication)/_components/AuthInput/AuthInput.module.scss
  src/app/(authentication)/_components/AuthInput/index.tsx
  src/app/(authentication)/_components/AuthSubmitButton/AuthSubmitButton.module.scss
  src/app/(authentication)/_components/AuthSubmitButton/index.tsx
  src/app/(authentication)/_components/SpeechBalloon/index.tsx
  src/app/(authentication)/layout.tsx
  src/app/(authentication)/signin/Signin.module.scss
  src/app/(authentication)/signin/page.tsx
  src/app/(authentication)/signup/Signup.module.scss
  src/app/(authentication)/signup/page.tsx
  src/app/globals.css
  src/app/globals.scss
  src/app/layout.tsx
  src/components/common/BackButton/index.tsx
  src/components/common/Input/Input.module.scss
  src/components/common/Input/index.tsx
  src/components/common/TagInput/TagInput.module.scss
  src/components/common/TagInput/index.tsx
  src/styles/reset.scss
Labels: enhancement

#48 Feat: 모임 생성 페이지 기능
  package-lock.json
  package.json
  public/assets/images/rectangle.png
  src/api/apis/gatheringsApis.ts
  src/api/instance.ts
  src/api/queryHooks/gathering.ts
  src/app/gatherings/new/New.module.scss
  src/app/gatherings/new/_components/Input/Input.module.scss
  src/app/gatherings/new/_components/Input/index.tsx
  src/app/gatherings/new/page.tsx
  src/app/gatherings/page.tsx
  src/app/gatherings/test.txt
  src/app/globals.scss
  src/app/test/song/datepicker/Example.module.scss
  src/app/test/song/datepicker/page.tsx
  src/app/test/song/gatherings/page.tsx
  src/app/test/song/page.tsx
  src/components/common/DatePicker/DatePicker.module.scss
  src/components/common/DatePicker/index.tsx
  src/components/common/FileInput/FileInput.module.scss
  src/components/common/FileInput/index.tsx
  src/components/common/Modal/Modal.module.scss
  src/components/common/TextEditor/index.tsx
  src/components/common/TextEditor/toolBarOptions.ts
  src/hooks/useFilePreview.ts
  src/hooks/useModal.ts
  src/utils/QueryKey.ts
  src/utils/isEqual.ts
  src/utils/react-query.ts
Labels: enhancement

#54 Feat: 로컬 로그인 / 회원가입 구현
  .eslintrc.json
  next.config.mjs
  src/api/apis/authApis.ts
  src/api/instance.ts
  src/api/queryHooks/auth.ts
  src/app/(authentication)/AuthLayout.module.scss
  src/app/(authentication)/_components/AuthHeader/AuthHeader.module.scss
  src/app/(authentication)/_components/AuthHeader/index.tsx
  src/app/(authentication)/_components/AuthInput/AuthInput.module.scss
  src/app/(authentication)/_components/AuthInput/index.tsx
  src/app/(authentication)/_components/AuthSubmitButton/AuthSubmitButton.module.scss
  src/app/(authentication)/_components/AuthSubmitButton/index.tsx
  src/app/(authentication)/_components/AuthTagInput/AuthTagInput.module.scss
  src/app/(authentication)/_components/AuthTagInput/index.tsx
  src/app/(authentication)/_components/SigninForm/SigninForm.module.scss
  src/app/(authentication)/_components/SigninForm/index.tsx
  src/app/(authentication)/_components/SignupForm/EmailSignupForm/EmailSignupForm.module.scss
  src/app/(authentication)/_components/SignupForm/EmailSignupForm/index.tsx
  src/app/(authentication)/_components/SignupForm/SocialSignupForm/SocialSignupForm.module.scss
  src/app/(authentication)/_components/SignupForm/SocialSignupForm/index.tsx
  src/app/(authentication)/_components/SignupForm/index.tsx
  src/app/(authentication)/_components/SpeechBalloon/index.tsx
  src/app/(authentication)/layout.tsx
  src/app/(authentication)/signin/Signin.module.scss
  src/app/(authentication)/signin/page.tsx
  src/app/(authentication)/signup/Signup.module.scss
  src/app/(authentication)/signup/page.tsx
  src/app/test/yong/test.txt
  src/components/common/BackButton/index.tsx
  src/components/common/Input/Input.module.scss
  src/components/common/Tag/Tag.module.scss
  src/components/common/Tag/index.tsx
  src/components/common/TagInput/TagInput.module.scss
  src/components/common/TagInput/index.tsx
  src/components/common/test.txt
  src/constants/test.txt
  src/hooks/test.txt
  src/hooks/useFunnel.tsx
  src/types/request/authRequestTypes.d.ts
  src/types/test.txt
Labels: enhancement

#57 Fix: 소셜 로그인 URL 수정
  src/app/(authentication)/signin/page.tsx
Labels: documentation

#45 Feat: 카카오지도 컴포넌트
  .eslintrc.json
  public/assets/icons/backArrow.svg
  public/assets/icons/search-zoom.svg
  src/api/queryHooks/geolocation.ts
  src/app/globals.scss
  src/app/layout.tsx
  src/components/common/BackButton/index.tsx
  src/components/common/FindPlaceModal/FindPlaceModal.module.scss
  src/components/common/FindPlaceModal/KakaoList/KakaoList.module.scss
  src/components/common/FindPlaceModal/KakaoList/PlaceListItem/PlaceListItem.module.scss
  src/components/common/FindPlaceModal/KakaoList/PlaceListItem/index.tsx
  src/components/common/FindPlaceModal/KakaoList/index.tsx
  src/components/common/FindPlaceModal/KakaoMap/KakaoMap.module.scss
  src/components/common/FindPlaceModal/KakaoMap/index.tsx
  src/components/common/FindPlaceModal/PlaceSearchBar/PlaceSearchBar.module.scss
  src/components/common/FindPlaceModal/PlaceSearchBar/index.tsx
  src/components/common/FindPlaceModal/index.tsx
  src/styles/color.scss
  src/styles/typography.scss
  src/types/kakao.d.ts
  src/utils/QueryKey.ts
  src/utils/calculateDistance.ts
  src/utils/kakaoSearch.ts
Labels: enhancement

#53 Feat: toast 구현
  src/app/layout.tsx
  src/components/common/ToastList/ToastList.module.scss
  src/components/common/ToastList/index.tsx
  src/contexts/toastContext.tsx
Labels: enhancement

#65 Feat: modal xButton Prop 추가
  public/assets/icons/x-button.svg
  src/app/test/song/modal/page.tsx
  src/components/common/Modal/Modal.module.scss
  src/components/common/Modal/index.tsx
Labels: enhancement

#71 Feat: 소셜로그인 및 카카오 지도 컴포넌트 리팩토링
  public/assets/images/firework.png
  src/api/apis/authApis.ts
  src/api/instance.ts
  src/api/queryHooks/auth.ts
  src/api/queryHooks/geolocation.ts
  src/app/(authentication)/_components/AuthSubmitButton/AuthSubmitButton.module.scss
  src/app/(authentication)/_components/AuthSubmitButton/index.tsx
  src/app/(authentication)/_components/AuthTagInput/AuthTagInput.module.scss
  src/app/(authentication)/_components/AuthTagInput/index.tsx
  src/app/(authentication)/_components/SigninForm/index.tsx
  src/app/(authentication)/_components/SignupForm/EmailSignupForm/index.tsx
  src/app/(authentication)/_components/SignupForm/SocialSignupForm/SocialSignupForm.module.scss
  src/app/(authentication)/_components/SignupForm/SocialSignupForm/index.tsx
  src/app/(authentication)/signin/Signin.module.scss
  src/app/(authentication)/signin/page.tsx
  src/app/(authentication)/signup/result/SignupResult.module.scss
  src/app/(authentication)/signup/result/page.tsx
  src/components/common/Button/Button.module.scss
  src/components/common/Button/index.tsx
  src/components/common/FindPlaceModal/FindPlaceModal.module.scss
  src/components/common/FindPlaceModal/KakaoList/PlaceListItem/PlaceListItem.module.scss
  src/components/common/FindPlaceModal/KakaoList/PlaceListItem/index.tsx
  src/components/common/FindPlaceModal/KakaoList/index.tsx
  src/components/common/FindPlaceModal/KakaoMap/KakaoMap.module.scss
  src/components/common/FindPlaceModal/KakaoMap/index.tsx
  src/components/common/FindPlaceModal/index.tsx
  src/components/common/Spinner/Spinner.module.scss
  src/components/common/Spinner/index.tsx
  src/components/common/Tag/index.tsx
  src/components/common/TagInput/TagInput.module.scss
  src/components/common/TagInput/index.tsx
  src/contexts/toastContext.tsx
Labels: enhancement

#73 Refactor: 소셜로그인 코드 수정 및 버그 수정
  src/actions/AuthActions.ts
  src/api/apis/authApis.ts
  src/app/(authentication)/_components/AuthTagInput/index.tsx
  src/app/(authentication)/_components/SigninForm/index.tsx
  src/app/(authentication)/_components/SignupForm/SocialSignupForm/index.tsx
  src/app/(authentication)/_components/SignupForm/index.tsx
  src/app/globals.scss
  src/components/common/FindPlaceModal/KakaoMap/index.tsx
  src/components/common/Tag/index.tsx
Labels: bug, enhancement

#91 Feat: 찜 api 구현
  public/assets/icons/clockIcon.svg
  public/assets/icons/mapPin.svg
  src/api/apis/wishListApis.ts
  src/api/queryHooks/wishList.ts
  src/app/globals.scss
  src/app/mypage/myFavoriteGatherings/myFavoriteGatherings.module.scss
  src/app/mypage/myFavoriteGatherings/page.tsx
  src/components/common/SaveGatheringButton/index.tsx
  src/types/response/WishListRES.ts
  src/utils/QueryKey.ts
Labels: enhancement

#86 Feat: 다른 유저 프로필 페이지 구현
  public/assets/icons/profileHeader.svg
  public/assets/icons/twoPeople.svg
  public/assets/images/defaultProfile.png
  src/api/apis/otherProfileApis.ts
  src/api/queryHooks/otherProfile.ts
  src/app/other-profile/[id]/OtherProfilePage.module.scss
  src/app/other-profile/[id]/_components/HeartRating/HeartRating.module.scss
  src/app/other-profile/[id]/_components/HeartRating/HeartUnit/index.tsx
  src/app/other-profile/[id]/_components/HeartRating/index.tsx
  src/app/other-profile/[id]/_components/MannerBar/MannerBar.module.scss
  src/app/other-profile/[id]/_components/MannerBar/index.tsx
  src/app/other-profile/[id]/_components/OtherProfileContents/OtherEvaluationTags/EvaluationgTag/EvaluationTag.module.scss
  src/app/other-profile/[id]/_components/OtherProfileContents/OtherEvaluationTags/EvaluationgTag/index.tsx
  src/app/other-profile/[id]/_components/OtherProfileContents/OtherEvaluationTags/OtherEvaluationTags.module.scss
  src/app/other-profile/[id]/_components/OtherProfileContents/OtherEvaluationTags/index.tsx
  src/app/other-profile/[id]/_components/OtherProfileContents/OtherProfileContents.module.scss
  src/app/other-profile/[id]/_components/OtherProfileContents/index.tsx
  src/app/other-profile/[id]/page.tsx
  src/components/common/DivSkeleton/DivSkeleton.module.scss
  src/components/common/DivSkeleton/index.tsx
  src/types/global.d.ts
  src/types/kakao.d.ts
  src/types/response/OtherProfileRES.d.ts
  src/utils/QueryKey.ts
Labels: enhancement

#97 Fix: 회원가입 TagInput 핫픽스
  src/components/common/TagInput/index.tsx
Labels: bug

#104 Fix: songeun 1차 QA 반영
  src/api/queryHooks/gathering.ts
  src/api/queryHooks/me.ts
  src/app/api/crawling/route.ts
  src/app/gatherings/[id]/_components/Footer/index.tsx
  src/app/gatherings/[id]/_components/GatheringDetails.tsx/index.tsx
  src/app/gatherings/[id]/_components/KakaoShare/index.tsx
  src/app/gatherings/[id]/_components/Members/index.tsx
  src/app/gatherings/[id]/_components/ShareModal/ShareModal.module.scss
  src/app/gatherings/new/New.module.scss
  src/app/gatherings/new/_components/GameDataList/GameDataList.module.scss
  src/app/gatherings/new/_components/GameDataList/index.tsx
  src/app/gatherings/new/page.tsx
  src/app/main/_components/gameRank/index.tsx
  src/app/mypage/_components/infoEdit/infoEdit.tsx
  src/app/recommend/page.tsx
  src/app/recommendAll/page.tsx
  src/app/recommendMany/page.tsx
  src/app/recommendSearch/_components/RecommendSearch/index.tsx
  src/app/recommendThree/page.tsx
  src/components/common/BottomSheet/index.tsx
  src/components/common/FileInput/index.tsx
  src/components/common/FindPlaceModal/FindPlaceModal.module.scss
  src/components/common/FindPlaceModal/KakaoList/PlaceListItem/index.tsx
  src/components/common/FindPlaceModal/KakaoList/index.tsx
  src/components/common/FindPlaceModal/KakaoMap/index.tsx
  src/components/common/FindPlaceModal/PlaceSearchBar/index.tsx
  src/components/common/FindPlaceModal/index.tsx
  src/components/common/Modal/index.tsx
  src/styles/reset.scss
  src/utils/debounce.ts
  src/utils/handleCopyClipBoard.ts
Labels: bug

#105 Fix: 다른 사람 프로필 페이지 핫픽스
  src/app/other-profile/[id]/_components/OtherProfileContents/index.tsx
Labels: bug

#106 Fix: 찜 버튼 오류 해결
  src/app/(authentication)/_components/AuthTagInput/index.tsx
  src/components/common/SaveGatheringButton/index.tsx
Labels: bug

#110 Feat: 소셜로그인 주석 처리 / userAgent 이용한 PC 확인 후 지도 스크롤 기능 추가
  src/app/(authentication)/signin/page.tsx
  src/components/common/FindPlaceModal/KakaoMap/index.tsx
  src/utils/isPC.ts
Labels: documentation, enhancement

#111 Design: 다른 유저 프로필 / 나의 찜 페이지 반응형
  src/app/mypage/myFavoriteGatherings/myFavoriteGatherings.module.scss
  src/app/other-profile/[id]/_components/OtherProfileContents/OtherEvaluationTags/EvaluationgTag/EvaluationTag.module.scss
  src/app/other-profile/[id]/_components/OtherProfileContents/OtherProfileContents.module.scss
  src/app/other-profile/[id]/_components/OtherProfileContents/index.tsx
  src/components/common/AccessControlBoundary/index.tsx
Labels: enhancement

#112 Design: AuthHeader 디자인 변경
  src/app/(authentication)/_components/AuthHeader/AuthHeader.module.scss
  src/app/(authentication)/_components/AuthHeader/index.tsx
Labels: enhancement

#115 Design: AuthHeader 반응형 디자인 재수정
  src/app/(authentication)/_components/AuthHeader/AuthHeader.module.scss
Labels: enhancement

#117 Fix/songeun 2
  src/app/gatherings/[id]/_components/GatheringDetails.tsx/index.tsx
  src/app/gatherings/[id]/_components/Members/index.tsx
  src/app/gatherings/[id]/page.tsx
  src/app/gatherings/new/_components/GameDataList/index.tsx
  src/app/gatherings/new/page.tsx
  src/app/gatherings/new/success/[id]/Success.module.scss
  src/app/gatherings/new/success/[id]/page.tsx
  src/app/other-profile/[id]/page.tsx
  src/components/common/BottomSheet/index.tsx
  src/components/common/DatePicker/index.tsx
  src/types/response/Gathering.ts
Labels: bug
