Repository LuckyVicky-2team/frontend, pull requests merged in 2024-10, with the labels that each got.

#137 Fix: Axios Interceptor 수정 및 약관동의 디자인 수정
  src/api/instance.ts
  src/app/(authentication)/_components/AuthTagInput/AuthTagInput.module.scss
  src/app/(authentication)/_components/AuthTagInput/index.tsx
  src/app/(authentication)/_components/SignupForm/ConsentForm/TermsItem/index.tsx
  src/app/(authentication)/_components/SignupForm/EmailSignupForm/EmailSignupForm.module.scss
  src/app/(authentication)/_components/SignupForm/SocialSignupForm/SocialSignupForm.module.scss
  src/app/(authentication)/_components/SignupForm/SocialSignupForm/index.tsx
  src/app/gatherings/[id]/_components/Members/index.tsx
  src/app/other-profile/[id]/page.tsx
  src/app/threads/[gatheringId]/page.tsx
  src/app/threads/_components/ThreadInput/index.tsx
  src/app/threads/page.tsx
  src/components/common/ToastList/ToastList.module.scss
  src/utils/getFormattedDate.ts
Labels: bug, enhancement

#141 Feat: Notification
  package-lock.json
  package.json
  public/assets/icons/apple_share.png
  public/assets/icons/trash.svg
  public/assets/images/logo2.png
  public/firebase-messaging-sw.js
  public/manifest.json
  src/api/apis/notification.ts
  src/api/queryHooks/notification.ts
  src/app/layout.tsx
  src/app/main/_components/Header/Header.tsx
  src/app/main/page.tsx
  src/app/mypage/_components/Info/Info.tsx
  src/app/notification/Notification.module.scss
  src/app/notification/page.tsx
  src/components/common/AppInstallPrompt/MobileInstallPrompt/MobileInstallPrompt.module.scss
  src/components/common/AppInstallPrompt/MobileInstallPrompt/index.tsx
  src/components/common/AppInstallPrompt/index.tsx
  src/components/common/BottomSheet/index.tsx
  src/service/foregroundMessage.ts
  src/service/initFirebase.ts
  src/service/notificationPermission.ts
  src/service/registerServiceWorker.ts
  src/types/response/notification.ts
  src/types/window.d.ts
  src/utils/QueryKey.ts
  tsconfig.json
Labels: enhancement

#147 Fix: songeun-5
  src/app/gatherings/[id]/_components/Footer/Footer.module.scss
  src/app/gatherings/[id]/_components/Footer/index.tsx
  src/app/gatherings/[id]/_components/GatheringDetails.tsx/GatheringDetails.module.scss
  src/app/gatherings/[id]/_components/GatheringDetails.tsx/index.tsx
  src/components/common/AppInstallPrompt/MobileInstallPrompt/index.tsx
  src/components/common/AppInstallPrompt/index.tsx
  src/components/common/Modal/LoginModal/LoginModal.module.scss
  src/components/common/Modal/LoginModal/index.tsx
  src/components/common/Modal/Modal.module.scss
  src/components/common/SaveGatheringButton/SaveGatheringButton.module.scss
  src/components/common/SaveGatheringButton/index.tsx
  src/hooks/useScreenWidth.ts
  src/service/notificationPermission.ts
Labels: bug

#150 Fix: songeun 6
  cypress/e2e/spec.cy.ts
  public/firebase-messaging-sw.js
  src/app/layout.tsx
  src/app/main/page.tsx
  src/service/foregroundMessage.ts
  src/service/foregroundMessage.tsx
  src/service/initFirebase.ts
  src/service/notificationPermission.ts
Labels: bug, enhancement

#151 Feat: 채팅 시스템 구현 및 리프레시 토큰 수정
  package-lock.json
  package.json
  src/actions/AuthActions.ts
  src/api/apis/threadApis.ts
  src/api/instance.ts
  src/api/queryHooks/thread.ts
  src/app/threads/ThreadsPage.module.scss
  src/app/threads/[chatRoomId]/ThreadDetailPage.module.scss
  src/app/threads/[chatRoomId]/page.tsx
  src/app/threads/[gatheringId]/ThreadDetailPage.module.scss
  src/app/threads/[gatheringId]/page.tsx
  src/app/threads/_components/ChattingRoom/ChattingRoom.module.scss
  src/app/threads/_components/ChattingRoom/index.tsx
  src/app/threads/_components/TalkListItem/TalkListItem.module.scss
  src/app/threads/_components/TalkListItem/index.tsx
  src/app/threads/_components/ThreadList/ThreadList.module.scss
  src/app/threads/_components/ThreadList/ThreadListItem/ThreadListItem.module.scss
  src/app/threads/_components/ThreadList/ThreadListItem/index.tsx
  src/app/threads/_components/ThreadList/index.tsx
  src/app/threads/page.tsx
  src/types/response/ChatroomsRES.ts
  src/utils/QueryKey.ts
Labels: enhancement
