Repository LuckyVicky-2team/frontend, pull requests merged in 2024-12, with the labels that each got.

#170 Feat: 채팅방 UI 수정 및 기능 구현
  src/actions/AuthActions.ts
  src/api/apis/authApis.ts
  src/api/instance.ts
  src/api/queryHooks/thread.ts
  src/app/(authentication)/_components/SignupForm/EmailSignupForm/index.tsx
  src/app/(authentication)/_components/SignupForm/SocialSignupForm/index.tsx
  src/app/mypage/myFavoriteGatherings/page.tsx
  src/app/threads/ThreadsPage.module.scss
  src/app/threads/_components/ChattingRoom/ChattingRoom.module.scss
  src/app/threads/_components/ChattingRoom/index.tsx
  src/app/threads/_components/GatheringInfoOfThread/GatheringInfoThread.module.scss
  src/app/threads/_components/GatheringInfoOfThread/index.tsx
  src/app/threads/_components/TalkListItem/TalkListItem.module.scss
  src/app/threads/_components/TalkListItem/index.tsx
  src/app/threads/_components/ThreadInput/ThreadInput.module.scss
  src/app/threads/_components/ThreadList/ThreadList.module.scss
  src/app/threads/_components/ThreadList/ThreadListItem/ThreadListItem.module.scss
  src/app/threads/_components/ThreadList/ThreadListItem/index.tsx
  src/app/threads/_components/ToBottomButton/ToBottomButton.module.scss
  src/app/threads/_components/ToBottomButton/index.tsx
  src/components/common/FindPlaceModal/index.tsx
  src/utils/formatTimeDiff.ts
Labels: enhancement

#176 Fix: 채팅방 스크롤 오류 수정 및 디버깅용 주석 추가
  src/app/(authentication)/_components/SignupForm/EmailSignupForm/index.tsx
  src/app/(authentication)/_components/SignupForm/SocialSignupForm/index.tsx
  src/app/threads/_components/ChattingRoom/index.tsx
Labels: bug

#178 Fix: 소셜회원가입 디버깅 코드 추가
  src/actions/AuthActions.ts
  src/app/(authentication)/_components/SignupForm/SocialSignupForm/index.tsx
  src/app/threads/_components/ChattingRoom/index.tsx
  src/app/threads/_components/TalkListItem/index.tsx
Labels: bug

#179 Fix: 소셜 회원가입 디버깅 코드 추가
  src/actions/AuthActions.ts
  src/api/instance.ts
  src/app/(authentication)/_components/SignupForm/SocialSignupForm/index.tsx
Labels: bug

#180 Fix: 소셜 회원가입 디버깅 코드 추가 - 3
  src/app/(authentication)/_components/SignupForm/SocialSignupForm/index.tsx
Labels: bug

#181 Fix: 소셜 회원가입 오류 수정 및 찜버튼 오류 수정
  src/actions/AuthActions.ts
  src/api/apis/authApis.ts
  src/api/instance.ts
  src/app/(authentication)/_components/SignupForm/SocialSignupForm/index.tsx
  src/components/common/SaveGatheringButton/index.tsx
  src/types/request/authRequestTypes.d.ts
Labels: bug

#182 Fix: 소셜 회원가입 오류 재수정
  src/api/instance.ts
Labels: bug

#183 Fix: 소셜 회원가입 디버깅 코드 추가 - 4
  src/actions/AuthActions.ts
  src/app/(authentication)/_components/SignupForm/SocialSignupForm/index.tsx
Labels: bug

#184 Fix: 소셜 회원가입 디버깅 코드 추가 - 5
  src/actions/AuthActions.ts
  src/app/(authentication)/_components/SignupForm/SocialSignupForm/index.tsx
Labels: bug

#186 Fix: songeun 14
  global.d.ts
  src/app/gatherings/[id]/_components/Footer/index.tsx
  src/app/gatherings/[id]/_components/GatheringDetails.tsx/GatheringDetails.module.scss
  src/app/gatherings/[id]/_components/GatheringForm/GatheringForm.module.scss
  src/app/gatherings/[id]/_components/GatheringForm/index.tsx
  src/app/gatherings/[id]/_components/Members/Members.module.scss
  src/app/gatherings/[id]/_components/Members/index.tsx
  src/app/gatherings/new/_components/GameDataList/GameDataList.module.scss
  src/app/gatherings/new/_components/GameDataList/index.tsx
  src/app/gatherings/new/_components/NumberInput/NumberInput.module.scss
  src/app/globals.scss
  src/components/common/AppInstallPrompt/MobileInstallPrompt/MobileInstallPrompt.module.scss
  src/components/common/AppInstallPrompt/MobileInstallPrompt/index.tsx
  src/components/common/AppInstallPrompt/index.tsx
  src/components/common/BottomSheet/BottomSheet.module.scss
  src/components/common/FCMDisabledPrompt/index.tsx
  src/components/common/Modal/index.tsx
  src/hooks/useScreenHeight.ts
  src/utils/getCookie.ts
Labels: bug, enhancement

#188 Fix: songeun-15
  src/app/gatherings/[id]/_components/Footer/index.tsx
  src/components/common/AppInstallPrompt/index.tsx
  src/components/common/BottomSheet/index.tsx
Labels: bug

#189 Refactor: UI 반응형 디자인 및 약관 프리렌더링
  src/api/apis/authApis.ts
  src/api/apis/logOutApis.ts
  src/api/queryHooks/auth.ts
  src/app/(authentication)/_components/AuthTitle/AuthTitle.module.scss
  src/app/(authentication)/_components/SignupForm/ConsentForm/TermsItem/TermsItem.module.scss
  src/app/(authentication)/_components/SignupForm/EmailSignupForm/index.tsx
  src/app/(authentication)/_components/SignupForm/SocialSignupForm/index.tsx
  src/app/(authentication)/_components/SignupForm/index.tsx
  src/app/mypage/myFavoriteGatherings/myFavoriteGatherings.module.scss
  src/app/mypage/settingAlarm/settingAlarm.module.scss
  src/app/other-profile/[id]/OtherProfilePage.module.scss
  src/app/other-profile/[id]/_components/OtherProfileBackButton/OtherProfileBackButton.module.scss
  src/app/other-profile/[id]/_components/OtherProfileBackButton/index.tsx
  src/app/other-profile/[id]/page.tsx
  src/app/threads/ThreadsPage.module.scss
Labels: enhancement

#193 Fix: 각종 오류 및 디자인 변경
  src/api/apis/logOutApis.ts
  src/app/(authentication)/_components/AuthHeader/AuthHeader.module.scss
  src/app/(authentication)/_components/SigninForm/index.tsx
  src/app/(authentication)/_components/SignupForm/EmailSignupForm/EmailSignupForm.module.scss
  src/app/(authentication)/_components/SignupForm/EmailSignupForm/index.tsx
  src/app/(authentication)/_components/SignupForm/SocialSignupForm/SocialSignupForm.module.scss
  src/app/(authentication)/_components/SignupForm/SocialSignupForm/index.tsx
  src/app/NotFoundPage.module.scss
  src/app/mypage/_components/Info/Info.tsx
  src/app/mypage/myFavoriteGatherings/page.tsx
  src/app/not-found.tsx
  src/app/threads/[chatRoomId]/ThreadDetailPage.module.scss
  src/app/threads/_components/ChattingRoom/ChattingRoom.module.scss
  src/app/threads/_components/ChattingRoom/index.tsx
  src/components/common/Modal/LoginModal/index.tsx
  src/components/common/ToastList/ToastList.module.scss
  src/contexts/toastContext.tsx
Labels: bug, enhancement

#196 Fix: 소셜 회원가입 / 채팅방 오류 수정
  src/api/apis/authApis.ts
  src/api/apis/threadApis.ts
  src/app/(authentication)/_components/SignupForm/SocialSignupForm/index.tsx
  src/app/api/logout/route.ts
  src/app/threads/_components/ChattingRoom/index.tsx
  src/components/common/AccessControlBoundary/index.tsx
Labels: bug, enhancement

#197 Fix: qa 수정 및 오류 수정
  src/api/instance.ts
  src/app/(authentication)/_components/SigninForm/index.tsx
  src/app/(authentication)/_components/SignupForm/SocialSignupForm/index.tsx
  src/app/layout.tsx
  src/app/main/_components/Header/Header.tsx
  src/app/main/page.tsx
  src/app/mypage/_components/Info/Info.tsx
  src/app/threads/_components/ChattingRoom/index.tsx
  src/components/common/AccessControlBoundary/index.tsx
  src/components/common/AppInstallPrompt/index.tsx
  src/hooks/useScreenHeight.ts
  src/utils/changeAccessToken.ts
  src/utils/getCookie.ts
Labels: bug, enhancement
